spring.application.name: core-api
spring.profiles.active: local

spring:
  config:
    import:
      - storage.yml
      - logging.yml
      - client-admin.yml

  web.resources.add-mappings: false

server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.winten: DEBUG
    org.springframework.data.redis: DEBUG
---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: local-dev


---
spring.config.activate.on-profile: dev


---
spring.config.activate.on-profile: staging


---
spring.config.activate.on-profile: live